project:
  type: website

website:
  title: "Kevin Rue-Albrecht"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    # link-external-icon: true
    link-external-newwindow: true
