---
title: "Curriculum Vitae"
---

**Kevin Rue-Albrecht, Computational Biologist (Dipl. Ing., Ph.D.)**

::: {.cv-section}
### Education

::: {.cv-entry}
::: {.cv-dates}
2011 - 2015
:::
::: {.cv-title}
DPhil, Computational Infection Biology
:::
::: {.cv-location}
University College Dublin (Ireland)
:::
::: {.cv-description}
**Thesis:** Comparative systems biology analyses of the bovine transcriptional response to species of the Mycobacterium genus.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2008 - 2011
:::
::: {.cv-title}
Ingénieur diplômé
:::
::: {.cv-location}
École Polytechnique Universitaire Polytech Nice-Sophia (France)
:::
::: {.cv-description}
**Major:** Bioinformatics and Modelling for Biology
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2006 - 2008
:::
::: {.cv-title}
Class Préparatoire aux Grandes Écoles BCPST-Véto
:::
::: {.cv-location}
Lycée Jean Rostand, Strasbourg (France)
:::
::: {.cv-description}
**BCPST:** Biology, Chemistry, Physics, Earth Sciences
:::
:::
:::

::: {.cv-section}
### Research Experience

::: {.cv-entry}
::: {.cv-dates}
2020 - present
:::
::: {.cv-title}
Computational Biologist & Biomedical Data Science Trainer
:::
::: {.cv-location}
[Sims Group](https://www.imm.ox.ac.uk/research/research-groups/sims-group-computational-genomics) (University of Oxford)
:::
::: {.cv-description}
Contributing to computational biology research and training programs in functional genomics and single-cell sequencing analysis.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2017 - 2020
:::
::: {.cv-title}
Postdoctoral Researcher - Computational Biology
:::
::: {.cv-location}
[Sansom Group](https://www.kennedy.ox.ac.uk/research/research-groups/computational-genomics) (University of Oxford)
:::
::: {.cv-description}
Contributed to the study of Inflammatory bowel disease pathogenesis and T-cell development through the development of computational pipelines for bespoke data analysis.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2016 - 2017
:::
::: {.cv-title}
Postdoctoral Researcher - Computational Biology
:::
::: {.cv-location}
[Ratcliffe Group](https://www.ludwig.ox.ac.uk/research/prof-sir-peter-ratcliffe-oxygen-sensing) (University of Oxford)
:::
::: {.cv-description}
Managed data and computational workflows for high-throughput sequencing projects including targeted DNA resequencing, ChIP-seq, and RNA-seq for renal cancer research.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
2015 - 2016
:::
::: {.cv-title}
Research associate - Bioinformatics & Biostatistics
:::
::: {.cv-location}
[Wilkins Group](https://profiles.imperial.ac.uk/m.wilkins) (Imperial College London)
:::
::: {.cv-description}
Managed data and computational workflows for high-throughput sequencing projects including targeted DNA resequencing, ChIP-seq, and RNA-seq for renal cancer research.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Apr 2012 -\
Jul 2012
:::
::: {.cv-title}
PhD Rotation Project (3 of 3) - Molecular biology
:::
::: {.cv-location}
[O'Gara Group](https://orcid.org/0000-0003-3866-7161) (University College Dublin)
:::
::: {.cv-description}
Evaluated the role of a gene candidate underlying *Staphylococcus aureus* antibiotic resistance by Sanger sequencing and biofilm assay.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jan 2012 -\
Apr 2012
:::
::: {.cv-title}
PhD Rotation Project (2 of 3) - Molecular biology
:::
::: {.cv-location}
[Ferguson Group](https://www.researchgate.net/scientific-contributions/Neil-Ferguson-38863526) (University College Dublin)
:::
::: {.cv-description}
Expressed and purified a Hepatitis B protein construct for experimental screening of interacting drug fragments.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Sep 2011 -\
Jan 2012
:::
::: {.cv-title}
PhD Rotation Project (1 of 3) - Molecular biology
:::
::: {.cv-location}
[Shield Group](https://people.ucd.ie/denis.shields/) / [Gordon Group](https://people.ucd.ie/stephen.gordon/) (University College Dublin)
:::
::: {.cv-description}
Predicted *Mycobacterium bovis* epitopes in cattle using *in silico* structure-based modelling.
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jun 2010 -\
Sep 2010
:::
::: {.cv-title}
Intern - Computational Biology
:::
::: {.cv-location}

[Shield Group](https://people.ucd.ie/denis.shields/) (University College Dublin)
:::
::: {.cv-description}
Analysed structural disorder in *Saccharomyces cerevisiae* interacting proteins.

Project supervisor: [Dr. Nora Khaldi](https://www.nuritas.com/team/dr-nora-khaldi/)

::: {.cv-publications}
<span class="pub-label">Publication:</span>
<div class="pub-item">[Correlation of disorder between *S. cerevisiae* interacting proteins](https://pubs.rsc.org/en/content/articlelanding/2012/mb/c1mb05214d)</div>
:::
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jul 2009 -\
Aug 2009
:::
::: {.cv-title}
Intern - Molecular Biology
:::
::: {.cv-location}
[INSERM, Unité Mixte de Recherche S725, Biologie des Cellules Dendritiques Humaines](https://academic.oup.com/jimmunol/article-abstract/188/8/3903/7981527) (Strasbourg, France)
:::
::: {.cv-description}
Expressed recombinant MHC class II molecules in HeLa cells.

Project supervisor: [Henri de la Salle](https://orcid.org/0000-0001-5136-0776)
:::
:::
:::

::: {.cv-section}
### Professional Experience

::: {.cv-entry}
::: {.cv-dates}
Oct 2022 -\
Oct 2023
:::
::: {.cv-title}
Software Developer Consultant
:::
::: {.cv-location}
Self-employed (Oxford, UK)
:::
::: {.cv-description}
Developed three extension packages in the iSEE framework for the analysis and visualisation of omics data sponsored by [Denali Therapeutics Inc](https://www.denalitherapeutics.com/).

- [iSEEindex](https://github.com/iSEE/iSEEindex)
- [iSEEde](https://github.com/iSEE/iSEEde)
- [iSEEpathways](https://github.com/iSEE/iSEEpathways)
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Apr 2011 -\
Jul 2011
:::
::: {.cv-title}
Software Developer Intern
:::
::: {.cv-location}
[MEDIT S.A.](https://www.linkedin.com/company/medit-sa/) (Palaiseau, France)
:::
::: {.cv-description}
Implemented functionality for structurally-constrained multiple alignment of protein sequences for the commercial software MED-SuMo.
:::
:::
:::

::: {.cv-section}
### Teaching Experience

::: {.cv-entry}
::: {.cv-dates}
Oct 2025
:::
::: {.cv-title}
R for data science and genomics
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Nine days of hands-on training covering R programming, data science principles, and genomic data analysis (11 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Sep 2025 -\
Oct 2025
:::
::: {.cv-title}
Genomics on the Linux command line
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Five days of hands-on training covering Linux command line tools for genomic data analysis (11 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Aug 2025
:::
::: {.cv-title}
Orchestrating Large-Scale Single-Cell Analysis with Bioconductor
:::
::: {.cv-location}
[The Carpentries](https://carpentries.org/) + [Bioconductor](https://www.bioconductor.org/)
:::
::: {.cv-description}
Two days of hands-on training covering the Bioconductor ecosystem for single-cell RNA-seq analysis (21 participants).

- [Event page](https://eurobioc2025.bioconductor.org/pages/carpentryworkshops.html)
- [Lesson materials](https://carpentries-incubator.github.io/bioc-scrnaseq/)
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jul 2024
:::
::: {.cv-title}
Spatial Transcriptomics data analysis using R
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Four days of hands-on training covering spatial transcriptomics data analysis (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jun 2025
:::
::: {.cv-title}
Introduction to single-cell RNAseq data analysis using R
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Six days of hands-on training covering single-cell analysis using Seurat and Bioconductor (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
May 2025
:::
::: {.cv-title}
R for data science and genomics
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Nine days of hands-on training covering R programming, data science principles, and genomic data analysis (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
May 2025
:::
::: {.cv-title}
Genomics on the Linux command line
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Five days of hands-on training covering Linux command line tools for genomic data analysis (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Feb 2025
:::
::: {.cv-title}
Introduction to single-cell RNAseq data analysis using Python
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Five days of hands-on training covering single-cell RNAseq data analysis using Python (12 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jan 2025
:::
::: {.cv-title}
Python programming and data science
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Six days of hands-on training covering Python programming and data science principles (7 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jan 2025
:::
::: {.cv-title}
Genomics on the Linux command line
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Five days of hands-on training covering Linux command line tools for genomic data analysis (9 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Dec 2024
:::
::: {.cv-title}
Containers for Reproducible Research
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
One day of hands-on training covering containerization technologies (e.g., Apptainer) for reproducible research (8 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Nov 2024
:::
::: {.cv-title}
Introduction to single-cell RNAseq data analysis using R
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Six days of hands-on training covering single-cell analysis using Seurat and Bioconductor (11 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Oct 2024
:::
::: {.cv-title}
R for data science and genomics
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Nine days of hands-on training covering R programming, data science principles, and genomic data analysis (14 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Sep 2024 -\
Oct 2024
:::
::: {.cv-title}
Genomics on the Linux command line
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Five days of hands-on training covering Linux command line tools for genomic data analysis (13 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Sep 2024
:::
::: {.cv-title}
Spatial Transcriptomics Data Camp
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Five days of hands-on training covering spatial transcriptomics data analysis (25 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Jun 2024
:::
::: {.cv-title}
Introduction to single-cell RNAseq data analysis using R
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Six days of hands-on training covering single-cell analysis using Seurat and Bioconductor (13 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
May 2024
:::
::: {.cv-title}
R for data science and genomics
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Nine days of hands-on training covering R programming, data science principles, and genomic data analysis (10 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Apr 2024-\
May 2024
:::
::: {.cv-title}
Genomics on the Linux command line
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Five days of hands-on training covering Linux command line tools for genomic data analysis (11 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Mar 2024
:::
::: {.cv-title}
Introduction to single-cell RNAseq data analysis using R
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Six days of hands-on training covering single-cell analysis using Seurat and Bioconductor (10 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Feb 2024-\
Mar 2024
:::
::: {.cv-title}
R for data science and genomics
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Nine days of hands-on training covering R programming, data science principles, and genomic data analysis (13 participants).
:::
:::

::: {.cv-entry}
::: {.cv-dates}
Feb 2024
:::
::: {.cv-title}
Genomics on the Linux command line
:::
::: {.cv-location}
[Oxford Biomedical Data Science (OBDS) Training Programme][obds-training]
:::
::: {.cv-description}
Five days of hands-on training covering Linux command line tools for genomic data analysis (11 participants).
:::
:::
:::

[obds-training]: https://www.imm.ox.ac.uk/research/units-and-centres/mrc-wimm-centre-for-computational-biology/training/oxford-biomedical-data-science-training-programme
